### ISSUE TITLE
Error after full setup

### ISSUE THREAD

**Issue by TerpToke** [AdriaGual/pokemon-pocket-bot#1]
After starting the bot I get this error, any advice?:

"Exception in thread Thread-1 (connect_and_run):
Traceback (most recent call last):
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\bot.py", line 52, in connect_and_run
    connect_to_emulator(self.app_state.emulator_name)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\adb_utils.py", line 8, in connect_to_emulator
    subprocess.run(["adb", "connect", emulator_name])
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 859, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType"
Exception in thread Thread-1 (connect_and_run):
Traceback (most recent call last):
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\bot.py", line 52, in connect_and_run
    connect_to_emulator(self.app_state.emulator_name)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\adb_utils.py", line 8, in connect_to_emulator
    subprocess.run(["adb", "connect", emulator_name])
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 859, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by AdriaGual** [comment]
Does the UI open?

And did you chose the path to your emulator?

There should be a configs.txt file generated in the project, is there config?

**Comment by 321098123** [comment]
I resolved this issue by adding the [shell=True](https://stackoverflow.com/questions/73193119) argument to all subprocess.run commands and registering LDPlayer's ADB in the system environment variables.

**Comment by TerpToke** [comment]
Thanks for getting back to me @AdriaGual !!!

The UI populates perfectly fine, this code below doesn't pop up until I hit "Start Bot".

I have my emulator name, I'm just not exactly sure where to put it. "emulator-5554"

Thank you for your work and support!

After updating to your latest pull I am now faced with a similar error:

"Error getting emulator name: [WinError 2] The system cannot find the file specified
Exception in thread Thread-1 (connect_and_run):
Traceback (most recent call last):
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\bot.py", line 76, in connect_and_run
    connect_to_emulator(emulator_name)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\adb_utils.py", line 8, in connect_to_emulator
    subprocess.run(["adb", "connect", emulator_name])
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 859, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType"

**Comment by TerpToke** [comment]
Hello!

Yes there is a config! :)

The UI opens!

Path is chosen correctly!

**Comment by AdriaGual** [comment]
@TerpToke If you already have the emulator name, you can open the `configs.txt` file and add:

```
path = "C:/LDPlayer/LDPlayer9"
emulator = "emulator-5554"
```

**Comment by TerpToke** [comment]
@AdriaGual Sadly it seems to be around the same issue. I even double checked my emulator name. 

C:\LDPlayer\LDPlayer9>adb devices
List of devices attached
emulator-5554   device

It may or may not help but I'm using a specific version of LDPlayer that was posted by the official "LDPlayer" Reddit profile to enable vulkan for Pokemon TCGP. The versions posted on their website did not work for this game for me. "https://res.ldrescdn.com/download/package/LDPlayer_9.1.25.1.exe"

Current error: 
"FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception in thread Thread-2 (connect_and_run):
Traceback (most recent call last):
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\bot.py", line 73, in connect_and_run
    connect_to_emulator(self.app_state.emulator_name)
  File "C:\Users\camer\Downloads\pokemon-pocket-bot-main\pokemon-pocket-bot-main\adb_utils.py", line 8, in connect_to_emulator
    subprocess.run(["adb", "connect", emulator_name])
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\camer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified"

**Comment by TerpToke** [comment]
> I resolved this issue by adding the [shell=True](https://stackoverflow.com/questions/73193119) argument to all subprocess.run commands and registering LDPlayer's ADB in the system environment variables.

Thanks for the tip @321098123 ! After going into subprocess.py and changing all shell=False to shell=True, along with adding LDPlayer's ADB into System Variables. It now seems like the bot wants to work but cmd states:

 "'adb' is not recognized as an internal or external command,
operable program or batch file." 

I am not entirely sure what the issue may be? (I took the screenshot right after trying it in battle)

Thank you for everyone's help. I'm very determined to get this to work!
![image_2024-11-05_015837874](https://github.com/user-attachments/assets/523ccc95-3e84-40e9-9fa7-acf1b6ccc16d)

**Comment by 321098123** [comment]
@TerpToke Does this work properly, by any chance? The image search for bench cards still isn't working correctly for me https://github.com/AdriaGual/pokemon-pocket-bot/issues/2#issue-2634009027

**Comment by AdriaGual** [comment]
@TerpToke You'll get it for sure, don't worry!

So, you can try to add the path to the adb (C:\LDPlayer\LDPlayer9) to the system variable called `Path`.
![image](https://github.com/user-attachments/assets/35950a25-30c0-4ff3-be79-0c00beed099e)

Also restart the computer after that.

Another thing I would do is to go to the root of the project folder and open a cmd there to see if I can run a `adb devices` there.

**Comment by AdriaGual** [comment]
@321098123 You tried changing the variable mentioned here? 
https://github.com/AdriaGual/pokemon-pocket-bot/issues/2#issuecomment-2455893904

Just in case, the pictures that the bot will take will be from the hand (it does a long press and then takes the screenshot), so just let the bot run, it'll save all the hand cards and then you choose the ones you need.

Hope it helps!

**Comment by TerpToke** [comment]
> @TerpToke You'll get it for sure, don't worry!
> 
> So, you can try to add the path to the adb (C:\LDPlayer\LDPlayer9) to the system variable called `Path`. ![image](https://private-user-images.githubusercontent.com/25803231/383065440-35950a25-30c0-4ff3-be79-0c00beed099e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjY4MTcsIm5iZiI6MTczMDg2NjUxNywicGF0aCI6Ii8yNTgwMzIzMS8zODMwNjU0NDAtMzU5NTBhMjUtMzBjMC00ZmYzLWJlNzktMGMwMGJlZWQwOTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA0MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNDkxN2U5ZjM2MzYwYWZjODJlZmU4N2U0NzlmNzFiN2I1YWQ4MGZmZWU3ZjFmYmYyNWVjMmE1MDI4NTUwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G51HQqtgQDlGPZh5R2EXmccPl3sTGh5qMnUduFShhtE)
> 
> Also restart the computer after that.
> 
> Another thing I would do is to go to the root of the project folder and open a cmd there to see if I can run a `adb devices` there.

That fixed it right up! I didn't realize I hadn't added it directly to Path. Going to start messing around with it now! Thank you kindly for your work and support. Keep it up! <3

**Comment by TerpToke** [comment]
> @TerpToke You'll get it for sure, don't worry!
> 
> So, you can try to add the path to the adb (C:\LDPlayer\LDPlayer9) to the system variable called `Path`. ![image](https://private-user-images.githubusercontent.com/25803231/383065440-35950a25-30c0-4ff3-be79-0c00beed099e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjY4MTcsIm5iZiI6MTczMDg2NjUxNywicGF0aCI6Ii8yNTgwMzIzMS8zODMwNjU0NDAtMzU5NTBhMjUtMzBjMC00ZmYzLWJlNzktMGMwMGJlZWQwOTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA0MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNDkxN2U5ZjM2MzYwYWZjODJlZmU4N2U0NzlmNzFiN2I1YWQ4MGZmZWU3ZjFmYmYyNWVjMmE1MDI4NTUwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G51HQqtgQDlGPZh5R2EXmccPl3sTGh5qMnUduFShhtE)
> 
> Also restart the computer after that.
> 
> Another thing I would do is to go to the root of the project folder and open a cmd there to see if I can run a `adb devices` there.

That fixed it right up! I didn't realize I hadn't added it directly to Path. Going to start messing around with it now! Thank you kindly for your work and support. Keep it up! <3
